version: '3.8'

services:
  # 前端应用
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_WS_URL=ws://localhost:3001/ws
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - liqpro-network

  # API服务（简化版）
  api-service:
    image: node:18-alpine
    working_dir: /app/services/api-service
    ports:
      - "3001:3001"
    volumes:
      - ./services/api-service:/app/services/api-service
    environment:
      - NODE_ENV=development
      - PORT=3001
    networks:
      - liqpro-network
    command: >
      sh -c "npm install && 
             npm run dev"

networks:
  liqpro-network:
    driver: bridge 