version: '3.8'

services:
  # Message broker
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "127.0.0.1:5672:5672"  # Only expose to localhost
      - "127.0.0.1:15672:15672"  # Only expose to localhost
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-${RANDOM_PASSWORD}}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - liqpro-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # API Gateway
  api-service:
    image: ${REGISTRY:-}liqpro-api-service:${TAG:-latest}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-admin}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-${RANDOM_PASSWORD}}
      - RABBITMQ_VHOST=/
      - API_KEY=${API_KEY:-${RANDOM_API_KEY}}
      - JWT_SECRET=${JWT_SECRET:-${RANDOM_JWT_SECRET}}
    depends_on:
      - rabbitmq
    networks:
      - liqpro-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  # Data Service
  data-service:
    image: ${REGISTRY:-}liqpro-data-service:${TAG:-latest}
    ports:
      - "127.0.0.1:3001:3001"  # Only expose to localhost
    environment:
      - NODE_ENV=production
      - PORT=3001
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-admin}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-${RANDOM_PASSWORD}}
      - RABBITMQ_VHOST=/
      - SOLANA_RPC_URL=${SOLANA_RPC_URL}
      - SOLANA_RPC_API_KEY=${SOLANA_RPC_API_KEY}
    depends_on:
      - rabbitmq
    networks:
      - liqpro-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Signal Service
  signal-service:
    image: ${REGISTRY:-}liqpro-signal-service:${TAG:-latest}
    ports:
      - "127.0.0.1:3002:3002"  # Only expose to localhost
    environment:
      - NODE_ENV=production
      - PORT=3002
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-admin}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-${RANDOM_PASSWORD}}
      - RABBITMQ_VHOST=/
      - DATA_SERVICE_URL=http://data-service:3001
    depends_on:
      - rabbitmq
      - data-service
    networks:
      - liqpro-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Scoring Service
  scoring-service:
    image: ${REGISTRY:-}liqpro-scoring-service:${TAG:-latest}
    ports:
      - "127.0.0.1:3003:3003"  # Only expose to localhost
    environment:
      - NODE_ENV=production
      - PORT=3003
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-admin}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-${RANDOM_PASSWORD}}
      - RABBITMQ_VHOST=/
      - DATA_SERVICE_URL=http://data-service:3001
    depends_on:
      - rabbitmq
      - data-service
    networks:
      - liqpro-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Agent Engine
  agent-engine:
    image: ${REGISTRY:-}liqpro-agent-engine:${TAG:-latest}
    ports:
      - "127.0.0.1:3004:3004"  # Only expose to localhost
    environment:
      - NODE_ENV=production
      - PORT=3004
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-admin}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-${RANDOM_PASSWORD}}
      - RABBITMQ_VHOST=/
      - DATA_SERVICE_URL=http://data-service:3001
      - SIGNAL_SERVICE_URL=http://signal-service:3002
      - SCORING_SERVICE_URL=http://scoring-service:3003
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
    depends_on:
      - rabbitmq
      - data-service
      - signal-service
      - scoring-service
    networks:
      - liqpro-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  # Nginx reverse proxy
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - api-service
    networks:
      - liqpro-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  liqpro-network:
    driver: bridge

volumes:
  rabbitmq-data: 