version: '3.8'

services:
  # Message broker
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - liqpro-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # API Gateway
  api-service:
    image: ${REGISTRY:-}liqpro-api-service:${TAG:-latest}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${ENVIRONMENT:-staging}
      - PORT=3000
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - RABBITMQ_VHOST=/
    depends_on:
      - rabbitmq
    networks:
      - liqpro-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Data Service
  data-service:
    image: ${REGISTRY:-}liqpro-data-service:${TAG:-latest}
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${ENVIRONMENT:-staging}
      - PORT=3001
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - RABBITMQ_VHOST=/
      - SOLANA_RPC_URL=${SOLANA_RPC_URL:-https://api.devnet.solana.com}
    depends_on:
      - rabbitmq
    networks:
      - liqpro-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Signal Service
  signal-service:
    image: ${REGISTRY:-}liqpro-signal-service:${TAG:-latest}
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=${ENVIRONMENT:-staging}
      - PORT=3002
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - RABBITMQ_VHOST=/
      - DATA_SERVICE_URL=http://data-service:3001
    depends_on:
      - rabbitmq
      - data-service
    networks:
      - liqpro-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Scoring Service
  scoring-service:
    image: ${REGISTRY:-}liqpro-scoring-service:${TAG:-latest}
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=${ENVIRONMENT:-staging}
      - PORT=3003
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - RABBITMQ_VHOST=/
      - DATA_SERVICE_URL=http://data-service:3001
    depends_on:
      - rabbitmq
      - data-service
    networks:
      - liqpro-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Agent Engine
  agent-engine:
    image: ${REGISTRY:-}liqpro-agent-engine:${TAG:-latest}
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=${ENVIRONMENT:-staging}
      - PORT=3004
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - RABBITMQ_VHOST=/
      - DATA_SERVICE_URL=http://data-service:3001
      - SIGNAL_SERVICE_URL=http://signal-service:3002
      - SCORING_SERVICE_URL=http://scoring-service:3003
    depends_on:
      - rabbitmq
      - data-service
      - signal-service
      - scoring-service
    networks:
      - liqpro-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  liqpro-network:
    driver: bridge

volumes:
  rabbitmq-data: 