version: '3.8'

services:
  agent-engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - LOG_LEVEL=debug
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VHOST=/
      - DATA_SERVICE_URL=http://data-service:3001
      - SIGNAL_SERVICE_URL=http://signal-service:3002
      - SCORING_SERVICE_URL=http://scoring-service:3003
    depends_on:
      - rabbitmq
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    networks:
      - liqpro-network
    command: ["npm", "run", "dev"]

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - liqpro-network

networks:
  liqpro-network:
    driver: bridge

volumes:
  rabbitmq-data: 