apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: liqpro
  labels:
    app: api-service
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: api-service
        image: liqpro/api-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "staging"
        - name: DATA_SERVICE_URL
          value: "http://data-service:3001"
        - name: SIGNAL_SERVICE_URL
          value: "http://signal-service:3002"
        - name: SCORING_SERVICE_URL
          value: "http://scoring-service:3003"
        - name: AGENT_SERVICE_URL
          value: "http://agent-engine:3004"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: liqpro
  labels:
    app: api-service
    environment: staging
spec:
  selector:
    app: api-service
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  type: ClusterIP 