version: '3.8'

services:
  # 前端应用
  frontend:
    image: node:18
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_WS_URL=ws://localhost:3001/ws
    networks:
      - liqpro-network
    command: >
      sh -c "apt-get update && apt-get install -y git && 
             npm install --include=dev && 
             npm run start"
    restart: unless-stopped

  # API服务
  api-service:
    image: node:18
    working_dir: /app/services/api-service
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=production
      - SIGNAL_SERVICE_URL=http://signal-service:3000
      - DATA_SERVICE_URL=http://data-service-real:3000
      - SCORING_SERVICE_URL=http://scoring-service:3000
      - AGENT_SERVICE_URL=http://agent-engine:3000
      - RABBITMQ_PORT=5672
      - MONGODB_URI=mongodb://mongodb:27017/liqpro
    networks:
      - liqpro-network
    depends_on:
      - mongodb
      - rabbitmq
    command: >
      sh -c "apt-get update && apt-get install -y git && 
             cd /app/libs/common && 
             npm install && 
             npm install -g typescript && 
             npm run build && 
             cd /app/services/api-service && 
             rm -rf node_modules &&
             npm install && 
             npm install -g typescript && 
             npm install --save-dev @types/node @types/express @types/jest && 
             npm start"
    restart: unless-stopped

  # 数据服务（真实版）
  data-service-real:
    build:
      context: .
      dockerfile: Dockerfile.data-service-real
    ports:
      - "3004:3000"
    environment:
      - PORT=3000
      - DATA_COLLECTION_INTERVAL=300000
      - MONGO_URI=mongodb://mongodb:27017/liqpro
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=liqpro
      - RABBITMQ_PASS=liqpro
      - SOLANA_RPC_ENDPOINT=https://api.mainnet-beta.solana.com
      - LOG_LEVEL=info
      - HOURLY_SNAPSHOTS_TO_KEEP=168
      - DAILY_SNAPSHOTS_TO_KEEP=90
      - WEEKLY_SNAPSHOTS_TO_KEEP=52
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongodb
      - rabbitmq
    restart: unless-stopped

  # 信号服务
  signal-service:
    image: node:18
    working_dir: /app/services/signal-service
    ports:
      - "3006:3000"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/liqpro
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - liqpro-network
    depends_on:
      - mongodb
      - rabbitmq
    command: >
      sh -c "apt-get update && apt-get install -y git && 
             cd /app/libs/common && 
             npm install && 
             npm install -g typescript && 
             npm run build && 
             cd /app/services/signal-service && 
             npm install && 
             npm install -g typescript && 
             npx tsc --skipLibCheck --skipDefaultLibCheck --excludeFiles \"**/__tests__/**\" && 
             node dist/server.js"
    restart: unless-stopped

  # 评分服务
  scoring-service:
    image: node:18
    working_dir: /app/services/scoring-service
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/liqpro
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - liqpro-network
    depends_on:
      - mongodb
      - rabbitmq
    command: >
      sh -c "apt-get update && apt-get install -y git && 
             cd /app/libs/common && 
             npm install && 
             npm install -g typescript && 
             npm run build && 
             cd /app/services/scoring-service && 
             rm -rf node_modules &&
             npm install && 
             npm install -g typescript && 
             npm install --save-dev @types/node @types/express @types/jest && 
             npm start"
    restart: unless-stopped

  # Agent引擎
  agent-engine:
    image: node:18
    working_dir: /app/services/agent-engine
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/liqpro
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - SIGNAL_SERVICE_URL=http://signal-service:3000
      - DATA_SERVICE_URL=http://data-service-real:3000
      - SCORING_SERVICE_URL=http://scoring-service:3000
    networks:
      - liqpro-network
    depends_on:
      - mongodb
      - rabbitmq
      - data-service-real
      - signal-service
      - scoring-service
    command: >
      sh -c "apt-get update && apt-get install -y git && 
             cd /app/libs/common && 
             npm install && 
             npm install -g typescript && 
             npm run build && 
             cd /app/services/agent-engine && 
             rm -rf node_modules &&
             npm install && 
             npm install -g typescript && 
             npm install --save-dev @types/node @types/express @types/jest && 
             npm install --no-save ../libs/common && 
             npm start"
    restart: unless-stopped

  # MongoDB数据库
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - liqpro-network
    restart: unless-stopped

  # RabbitMQ消息队列
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=liqpro
      - RABBITMQ_DEFAULT_PASS=liqpro_password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - liqpro-network
    restart: unless-stopped

networks:
  liqpro-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  mongodb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/mongodb
  rabbitmq-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/rabbitmq 
