apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    uid: prometheus

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[liqpro-logs-]YYYY.MM.DD"
    jsonData:
      esVersion: 7.10.0
      timeField: "@timestamp"
      interval: Daily
    editable: false
    uid: elasticsearch 