name: Test and Update Version

on:
  push:
    branches: [main]
    paths:
      - 'services/agent-engine/**'
      - 'libs/**'
  pull_request:
    branches: [main]
    paths:
      - 'services/agent-engine/**'
      - 'libs/**'
  workflow_dispatch:

jobs:
  test-and-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: cd services/agent-engine && npm test
      
      - name: Update version if on main branch
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          npm run update-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 